### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/lmdb-rs#38] opened 2019-03-28 14:47 UTC
For the newly added `set_map_size()` and `info()`.

Thanks!

**Comment by mykmelez** [comment] 2019-03-28 19:30
Version string update in progress over in #39.

**Comment by mykmelez** [comment] 2019-03-29 00:19
After a delay caused by a Travis CI issue, builds passed, I merged the version update, and I built and published the new version:

https://crates.io/crates/lmdb-rkv/0.11.3

And I tagged it:

https://github.com/mozilla/lmdb-rs/tree/0.11.3

**Closed by mykmelez** 2019-03-29 00:19 UTC

**Comment by ncloudioj** [comment] 2019-03-29 13:46
Excellent! Thanks!
